Create workflow for CI
ontodev/gizmos pull request #19
Opened 2020-09-15 14:16 UTC by beckyjackson

This should run any time a push or pull request is made on `master`. It just runs everything in `tests`.

2020-09-18 19:01 UTC, jamesaoverton requested changes
The filename `python-package.yml` and the `on` `master` suggests that this was intended for releasing to PyPI, but the content is a CI test. We want both eventually, and as a CI test it works. I would rename this to `python-test.yml`.

2020-09-18 22:02 UTC, beckyjackson commented on .github/workflows/python-package.yml
> +on:
It also runs on pull requests to master, which is why it ran on this branch. Do we want to do more than pull requests to master?

2020-09-19 14:09 UTC, jamesaoverton commented on .github/workflows/python-package.yml
> +on:
I think we want CI to run on every push.

2020-09-19 23:55 UTC, beckyjackson commented on .github/workflows/python-package.yml
> +on:
OK - I've updated this

2020-09-21 19:40 UTC, jamesaoverton approved these changes

2020-09-21 19:40 UTC, merged