Replace sqlite3 and psycopg2 with sqlalchemy
ontodev/gizmos pull request #89
Opened 2021-07-16 03:19 UTC by beckyjackson

Resolves #82 

We should be able to use Gizmos without including `psycopg2` in requirements, unless we're connecting to a PostgreSQL database.

I added a bunch of type hinting to make it easier to ensure we're passing and returning the correct objects. It doesn't change how the code runs at all, but I can remove it if preferred.

2021-07-29 16:11 UTC, jamesaoverton requested changes
The `requirements.txt` still includes `psycopg2`, but we're trying to make it optional #82. When I remove it, `pytest -k sqlite` passes. I think the GitHub action for Postgres would need to be updated to install `psycopg2`.

Please add a note on running Posgres in Docker for testing like this: `docker run --rm -e POSTGRES_PASSWORD=postgres -p 5432:5432 postgres`

2021-07-29 16:26 UTC, beckyjackson commented
@jamesaoverton I've removed `psycopg2` and updated the README with more details on running with Postgres.

2021-08-03 19:06 UTC, jamesaoverton approved these changes

2021-08-03 19:21 UTC, jamesaoverton approved these changes
I didn't review all the code, but I tested locally and it seemed to work. Please merge!

2021-08-03 19:21 UTC, merged